window._CCSettings = {
    platform: "wechatgame",
    groupList: ["default"],
    collisionMatrix: [[true]],
    rawAssets: {
        assets: {
            "1": ["resources/Prefabs/btnMore.prefab", 1],
            "2": ["resources/Prefabs/startAd.prefab", 1],
            "4": ["resources/Prefabs/endAds.prefab", 1],
            "7": ["resources/Prefabs/listGamePanel.prefab", 1],
            "8": ["resources/Prefabs/moreGameList.prefab", 1],
            "10": ["resources/Prefabs/gameItem.prefab", 1],
            "11": ["resources/Prefabs/boxItem.prefab", 1],
            "13": ["resources/Texture/gameBox/gamebox_0", 2, 1],
            "c4PJ6tzE9GioTALY/Po6Cw": ["Texture/end/endClose.png", 0],
            "aa0L2+BJpF4YJK7nF1tdDV": ["Texture/end/endPanel.png", 0],
            "38bNQ/5KJGMphsTpaTBb4v": ["Texture/gameList/btnMore.png", 0],
            "5230kdQLpG4Ld5TGzqIiKc": ["Texture/gameList/icon.jpg", 0],
            "19rVE1gWZAqa/S9ADGhqx1": ["Texture/gameList/listPanel.png", 0],
            "27n2pjLIlPpo7GSZJgsfhZ": ["Texture/launch.png", 0],
            "baJSsiPdBPlLI+K0TcvwRi": ["Texture/more/more.png", 0],
            edifk1iKFGY7kCmPyLTifU: ["Texture/start/btnClose.png", 0],
            "16fbiOqQNLfJEvdEwCI7mO": ["Texture/start/startGame.png", 0],
            "7154qKAQ5OwYJ9ZqVccGsS": ["resources/Texture/gameBox/gamebox_0.png", 0],
            "bcZJ9m+1JMALZFuEZzZ4g3": ["resources/Texture/gameBox/gamebox_1", 2, 1],
            "a1exeCXcRN/Z5zJFpKYMDn": ["resources/Texture/gameBox/gamebox_1.png", 0],
            "4b2pE65lNF15BNNiAHDJxa": ["resources/Texture/gameBox/gamebox_2", 2, 1],
            "99eXHBwo9GB5hTshQWtDUI": ["resources/Texture/gameBox/gamebox_2.png", 0],
            b0IDo0xA5HvZyWePXErEUV: ["resources/Texture/gameBox/gamebox_3", 2, 1],
            "0cH9QCIrZAk7Lx3Uy8g23k": ["resources/Texture/gameBox/gamebox_3.png", 0],
            "2eF09F/zpKjZAMfpu3pJLN": ["resources/Texture/gameBox/gamebox_4", 2, 1],
            baGkRNcEhGHJpotW7GhuoF: ["resources/Texture/gameBox/gamebox_4.png", 0],
            "7bpUwhINZO4IieAoBFnC2h": ["resources/Texture/gameBox/gamebox_5", 2, 1],
            "a3p+yf48BDKqWCWhmPhpox": ["resources/Texture/gameBox/gamebox_5.png", 0],
            "ddeyEKfzRGDLTgG5aQT+9i": ["resources/Texture/gameBox/gamebox_6", 2, 1],
            b9kFGIZhNDp4vsROf5caFD: ["resources/Texture/gameBox/gamebox_6.png", 0],
            "68lCibpllC1rDdzcb3qfzp": ["resources/Texture/gameBox/gamebox_7", 2, 1],
            "0d/mc9RYFPu6EiKYZIAGVM": ["resources/Texture/gameBox/gamebox_7.png", 0],
            "06M0sXV49LTIhP1ON6OldQ": ["resources/Texture/gameBox/gamebox_8", 2, 1],
            "3a+hVoRSVIK45KYIzao9i4": ["resources/Texture/gameBox/gamebox_8.png", 0],
            "1es9tcj3NHlrcsZ+RY+muo": ["resources/Texture/gameBox/gamebox_9", 2, 1],
            bdqiNHoCdFObuBH7hUO1Gl: ["resources/Texture/gameBox/gamebox_9.png", 0]
        },
        internal: {
            "71VhFCTINJM6/Ky3oX9nBT": ["image/default_btn_disabled.png", 0],
            "e8Ueib+qJEhL6mXAHdnwbi": ["image/default_btn_normal.png", 0],
            "b4P/PCArtIdIH38t6mlw8Y": ["image/default_btn_pressed.png", 0],
            d608qFRoFHwbXd0Dap056i: ["image/default_scrollbar_vertical.png", 0],
            "61cyPdEfRN047sDK9rO0W5": ["image/default_scrollbar_vertical_bg.png", 0],
            "02delMVqdBD70a/HSD99FK": ["image/default_sprite_splash.png", 0]
        }
    },
    assetTypes: ["cc.Texture2D", "cc.Prefab", "cc.SpriteFrame"],
    launchScene: "db://assets/scenes/launch.fire",
    scenes: [{url: "db://assets/scenes/launch.fire", uuid: 9}, {url: "db://assets/scenes/gameBox.fire", uuid: 0}],
    packedAssets: {
        "0171e148b": [5, 6, 0, 3],
        "042d6d992": ["668anH1f9JBLUTiYHO2oXA", 1],
        "05f594864": ["29FYIk+N1GYaeWH/q1NxQO", 2, 3, "e97GVMl6JHh5Ml5qEDdSGa", "f0BIwQ8D5Ml7nTNQbh1YlS", "f0GZ9XhHNO+ZovZyUNeDzy", "f2J+M/3PFHwo4V0Zdg/dmq"],
        "06df81cad": ["3fkV94uNtMlKQZPFTg+Q+W", "ceZhtmwHFL5q5jzHr9YSAe", 4],
        "0821982b0": ["21JRbU6llL9rZzuicV7yrz", 5, 6, "efxYAKZvZE+qmGXa5rK3na", 7],
        "0a8aa695b": [8, 3],
        "0b0e00552": [9, "cf7bUpzGJAm7m5b2MH1fQq"],
        "0d382cb2f": [12, 10],
        "0eb15c935": [11, 12, 3, 13]
    },
    orientation: "",
    uuids: ["a0YejbpOVElLyJTuO1gwwR", "a7/20K00xJzqmXodWVUxjz", "73ky7FcBVMRrMCvff7UNj2", "a2MjXRFdtLlYQ5ouAFv/+R", "e8fyNfPpFEYa1409sNs+vW", "5cO7kybDxGj4ipyMYdRYZB", "5f5dyqtRNNxaFmVzYns6FZ", "f2BtoFxyJIFajGla6pslMF", "68ACiY+7ZBh5VW5TVOEp8e", "afrVjD3zVM5rZ3sPb6NK+b", "81kGwx7J1KE4PtnX5AI+HP", "3cS8uhhYZM6p8cTRtZFOd7", "6dgZQ5FHxPsYSMPdlgBlFw", "abN5Gulq5LU5qgRG3ZMNa1"]
};